version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Cambiado de "80:80" a "8080:80"
  
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
