version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - gruman_network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mariadb
    environment:
      TYPEORM_CONNECTION: mariadb
      #TYPEORM_HOST: 138.255.103.35
      TYPEORM_HOST: mariadb
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: gruman
      TYPEORM_PASSWORD: gruman
      TYPEORM_DATABASE: gruman
      JWT_SECRET: Law8XT1LW5SErt8CfHKifZwKSza6MTXU
    command: npm run start:dev
    networks:
      - gruman_network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: gruman
      MYSQL_DATABASE: gruman
      MYSQL_USER: gruman
      MYSQL_PASSWORD: gruman
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gruman_network

volumes:
  mariadb_data:

networks:
  gruman_network:
    driver: bridge
