version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - gruman_network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mariadb
    env_file:
      - ./backend/.env
    command: npm run start:dev
    networks:
      - gruman_network  

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: gruman
      MYSQL_DATABASE: gruman
      MYSQL_USER: gruman
      MYSQL_PASSWORD: gruman
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gruman_network

volumes:
  mariadb_data:

networks:
  gruman_network:
    driver: bridge
