name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List server directories
        run: |
          ls -la
      - name: Pull latest changes
        run: |
          git pull origin main
