name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List server directories
        run: |
          ls -la
      - name: Pull latest changes
        run: |
          git pull origin main

      

      - name: Docker compose build
        run: |
          sudo docker-compose build

      - name: Run Docker Compose
        run: |
          sudo docker-compose docker-compose.yml up

      - name: Run docker ps
        run: |
          docker ps

